# <font color=red> CODE CHALLENGES </font>

$\textbf{Code Challenges}$

1. Develop a python function from scratch that will find the determinants of any $n \times n$ matrix.

2. Develop a python function from scratch that will find both the eigenvectors and eigenvalues of any $n \times n$ matrix.

3. Test your functions from a randomly generated $n \times n$ matrix.

**1. Develop a python function from scratch that will find the determinants of any $n \times n$ matrix.**

In [1]:
def mat_det(A):
    assert len(A) == 0 or all(isinstance(row, list) for row in A) and len(A) == len(A[0]), "A should be a square matrix."

    n = len(A)
    if n == 0:
        return 1.
    elif n == 1:
        return A[0][0]
    elif n == 2:
        return A[0][0] * A[1][1] - A[0][1] * A[1][0]

    return sum((-1) ** col * cofactor * mat_det([[A[i][j] for j in range(n) if j != col] for i in range(1, n)]) for col, cofactor in enumerate(A[0]))


**2. Develop a python function from scratch that will find both the eigenvectors and eigenvalues of any $n \times n$ matrix.**

In [5]:
def normalize_vector(vector):
    norm = sum(a ** 2 for a in vector) ** 0.5
    return [a / norm for a in vector]

def dot_product(vec1, vec2):
    return sum(a * b for a, b in zip(vec1, vec2))

def subtract_matrices(mat1, mat2):
    return [[a - b for a, b in zip(row1, row2)] for row1, row2 in zip(mat1, mat2)]

def find_eigen(A, max_iterations=50000):
    assert len(A) == 0 or all(isinstance(row, list) for row in A) and len(A) == len(A[0]), "A should be a square matrix."

    n = len(A)
    if n == 0:
        return [], []
    if n == 1:
        return [A[0][0]], [[1.]]

    eigenvectors = []
    eigenvalues = []

    for _ in range(n):
        eigvec = [1.0] * n  # Initialize with a simple vector
        eigvec = normalize_vector(eigvec)

        for _ in range(max_iterations):
            tf_eigvec = [dot_product(row, eigvec) for row in A]
            eigvec = normalize_vector(tf_eigvec)

        eigval = dot_product(tf_eigvec, eigvec)
        eigenvalues.append(eigval)
        eigenvectors.append(eigvec)

        eigenval_outer_product = [[a * b for b in eigvec] for a in tf_eigvec]
        A = subtract_matrices(A, eigenval_outer_product)

    return eigenvalues, [list(row) for row in zip(*eigenvectors)]


**3. Test your functions from a randomly generated $n \times n$ matrix.**

In [9]:
import numpy as np

def custom_det(matrix):
    pass

A = np.random.random((8, 8)) * 5

custom_det_value = custom_det(A.tolist())
numpy_det_value = np.linalg.det(A)

print("Matrix:\n", A, "\n\nFrom Custom Determinant Func:\n", custom_det_value, "\n\nFrom Numpy Determinant:\n", numpy_det_value)


Matrix:
 [[4.17702314 4.0639323  4.03016278 3.42730606 2.36679024 0.52072567
  3.88342386 3.8895354 ]
 [0.34383946 2.83257032 3.94939177 3.75161927 3.54892069 2.1664017
  2.37407464 4.3921358 ]
 [0.76598432 2.7799864  3.08414078 4.10623266 4.24477405 2.14489233
  3.68873636 2.11430925]
 [4.18334362 2.75596457 3.62613175 4.65856765 0.78257081 1.1323523
  0.84335007 0.0274773 ]
 [3.76937907 4.60220689 3.70512872 1.97750392 0.26921933 2.66993505
  4.06830733 3.43113447]
 [1.61711471 1.03971534 4.43270141 3.73033864 2.17978685 1.67848981
  1.54117757 0.00581443]
 [0.563726   3.62840914 2.50471135 4.06916614 0.58042001 0.53865184
  0.95874529 3.26075301]
 [2.33674871 3.61395389 4.59447041 0.72270956 1.76999457 1.25258252
  4.32126019 1.93184757]] 

From Custom Determinant Func:
 None 

From Numpy Determinant:
 -7762.681112608337


**Eigenvalue**

In [10]:
import numpy as np

def find_eigen(matrix):
    pass

A = np.random.random((3, 3)) * 5

np_ev, np_evl = np.linalg.eig(A)
m_ev, m_evl = np.array(find_eigen(A.tolist())), np.array(find_eigen(A.tolist()))

print("Matrix:\n", A, "\n\nFrom custom Eigen Func:\n", m_ev, m_evl, "\n\nFrom numpy Eigen:\n", np_ev, np_evl)


Matrix:
 [[3.89129528 0.22592246 0.21107773]
 [4.35836706 1.29366177 1.90363061]
 [2.90941794 4.61632564 2.11733629]] 

From custom Eigen Func:
 None None 

From numpy Eigen:
 [ 5.65218875  2.91828935 -1.26818476] [[ 0.16767067  0.27247743 -0.0073152 ]
 [ 0.53056618 -0.32862785 -0.5883703 ]
 [ 0.83089474 -0.90430072  0.80855852]]
