In [9]:
# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

# <font color = red> ASSIGNMENT 1</font>
- The above python functions are developed to automate forward elimination.
- To complete the process of determining the solution, create a function or steps of function that will automate backward substitution.

In [10]:
import numpy as np

def row_swap(A, k, l):
    
    B = np.copy(A).astype('float64')
    B[[k, l], :] = B[[l, k], :]
    return B

def row_scale(A, k, scale):
   
    B = np.copy(A).astype('float64')
    B[k, :] *= scale
    return B

def row_add(A, k, l, scale):
   
    B = np.copy(A).astype('float64')
    B[l, :] += B[k, :] * scale
    return B

def backward_substitution(A, b):
   
    n = A.shape[0]
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        sum_ax = np.dot(A[i, i+1:], x[i+1:])
        x[i] = (b[i] - sum_ax) / A[i, i]

    return x

A = np.array([[1, -1, 1, 3], [2, 1, 8, 18], [4, 2, -3, -2]])

# Add -2 times row 0 to row 1
A1 = row_add(A, 0, 1, -2)
print("A1")
print(A1, '\n')

# Add -4 times row 0 to row 2
A2 = row_add(A1, 0, 2, -4)
print("A2")
print(A2, '\n')

# Add -2 times row 1 to row 2
A3 = row_add(A2, 1, 2, -2)
print("A3")
print(A3, '\n')

# Multiply row 1 by 1/3
A4 = row_scale(A3, 1, 1.0/3)
print("A4")
print(A4, '\n')

# Multiply row 2 by 1/19
A5 = row_scale(A4, 2, 1.0/-19.)
print("A5")
print(A5, '\n')

# Use the backward substitution to find the solutions
solutions = backward_substitution(A5[:, :-1], A5[:, -1])
# Print the solutions
for i, sol in enumerate(solutions):
    print(f"x{i + 1} = {sol}")


A1
[[ 1. -1.  1.  3.]
 [ 0.  3.  6. 12.]
 [ 4.  2. -3. -2.]] 

A2
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   6.  -7. -14.]] 

A3
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   0. -19. -38.]] 

A4
[[  1.  -1.   1.   3.]
 [  0.   1.   2.   4.]
 [  0.   0. -19. -38.]] 

A5
[[ 1. -1.  1.  3.]
 [ 0.  1.  2.  4.]
 [-0. -0.  1.  2.]] 

x1 = 1.0
x2 = 0.0
x3 = 2.0


# <font color = red> Assignment 2 </font>
---
**INSTRUCTION**
- Use latex programming to show your manual solutions.
- If the problem involves determining the row echelon or reduced row echelon, show both the manual and the pythonic solutions.
- Solutions must be saved as a jupyter notebook.
- Push your solutions to your forked github repo.
- Note that there is some **possibility** that some ,or all, of your exam questions will be taken from these assignment.
- The technique here is to first solve manually before writing in Latex.
---
1. Provide reasons why each of the following equations is, or is not, a linear equation.
- $\cos{\theta}x+4y+z = \sqrt{3}$
- $cos{x}4y+z = \sqrt{3}$
- $x^{-1}+7y+z = \sin{(\frac{\pi}{2})}$
- $x^1+y^1+z^1=0$
---
2. Find the solutions to the linear equations:
- $2x_1+3x_2 =5$
- $4x_1+3x_2+2x_3=1$
- $3x-6y=0$
---
3. Solve the following systems of linear equations<br>
a.<br> 
\begin{equation}
x-y=0 \\
2x+y = 3
\end{equation}
<br>
<br>
b. <br>
\begin{equation}
x+5y= -1 \\
-x+y = -5 \\
2x+4y = 4
\end{equation}
c. <br>
\begin{equation}
2x_1+3x_2-x_3= -1 \\
x_1+x_3 = 0 \\
-x_1+2x_2-2x_3 = 0
\end{equation}
<br>
---
4. Provide reasons why the given matrices are either a row echelon, a reduced row echelon, or niether both.<br>
a. <br>
\begin{pmatrix}
   1 & 0 & 1 \\
   0 & 0 & 3 \\
   0 & 1 & 0 \\
\end{pmatrix}<br><br>
b. <br>
\begin{pmatrix}
   7 & 0 & 1 & 0 \\
   0 & 1 & -1 & 4 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}<br><br>
c. <br>
\begin{pmatrix}
   0 & 1 & 3 & 0 \\
   0 & 0 & 0 & 1 \\
\end{pmatrix}<br><br>
d. <br>
\begin{pmatrix}
   0 & 0 & 0 \\
   0 & 0 & 0 \\
   0 & 0 & 0 \\
\end{pmatrix}<br><br>
e. <br>
\begin{pmatrix}
   1 & 0 & 3 & -4 & 0 \\
   0 & 0 & 0 & 0 & 0 \\
   0 & 1 & 5 & 0 & 1 \\
\end{pmatrix}<br><br>
f. <br>
\begin{pmatrix}
   0 & 0 & 1 \\
   0 & 1 & 0 \\
   1 & 0 & 0 \\
\end{pmatrix}<br><br>
g. <br>
\begin{pmatrix}
   1 & 2 & 3 \\
   1 & 0 & 0 \\
   0 & 1 & 1 \\
   0 & 0 & 1 \\
\end{pmatrix}<br><br>
h. <br>
\begin{pmatrix}
   2 & 1 & 3 & 5 \\
   0 & 0 & 1 & -1 \\
   0 & 0 & 0 & 3 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}
<br><br>
---
5. Solve the following systems of linear equations<br>
a.<br> 
\begin{equation}
x_1+2x_2-3x_3=9 \\
2x_1-x_2-x_3=0 \\
4x_1-x_2+x_3=4 \\
\end{equation}
<br>
<br>
b. <br>
\begin{equation}
x+2y= -1 \\
2x+y+z = 1 \\
-x+y-z = -1
\end{equation}
c. <br>
\begin{equation}
x_1-3x_2-2x_3=0 \\
-x_1+2x_2+x_3=0 \\
2x_1+4x_2+6x_3=0 \\
\end{equation}
<br>
d. <br>
\begin{equation}
w+x+2y+z=1 \\
w-x-y+z=0 \\
x+y=1 \\
w+x+z=2
\end{equation}
<br>
---
6. Determine if the vectors are linear combinations<br>
a. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} -1 \\ 3 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 2 \\ -6 \end{bmatrix}\\
\end{equation}
<br><br>
b. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}
<br><br>
c. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 3 \\ 1 \\ -2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}
<br><br>
---
7. Show that the following vectors are a span: <br>
a.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 1 \\ \end{bmatrix}
\begin{bmatrix}1 \\ -1 \\ \end{bmatrix}
\end{pmatrix}
$
<br><br>
b.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
<br><br>
c.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
<br><br>
---
8. Show that the following vectors are linearly independent:<br>
a. <br>
\begin{equation}
\begin{bmatrix} 3 \\ -1 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} -1 \\ 2 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 1 \\ 1 \\ 3 \\ 1 \end{bmatrix}
\begin{bmatrix} -1 \\ -1 \\ 1 \\ 3 \end{bmatrix}
\end{equation}
b. <br>
\begin{equation}
\begin{bmatrix} 0 \\ 0 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 0 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 4 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\end{equation}
<br>
c. <br>
\begin{equation}
\begin{bmatrix} 1 \\ -1 \\ 1 \\ 0 \end{bmatrix}
\begin{bmatrix} -1 \\ 1 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 1 \\ 0 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 0 \\ 1 \\ -1 \\ 1 \end{bmatrix}
\end{equation}

In [1]:
# Assignment 2.A

from sympy import symbols, Eq, solve, pprint

x1, x2 = symbols("x1 x2")
equation = Eq(2 * x1 + 3 * x2, 5)
solution = solve(equation, (x1, x2))

# Print
pprint("Solution:")
pprint(solution)



Solution:
⎡⎛5   3⋅x₂    ⎞⎤
⎢⎜─ - ────, x₂⎟⎥
⎣⎝2    2      ⎠⎦


In [2]:
# Assignment 2.B

import sympy as sp


x1, x2, x3 = sp.symbols("x1 x2 x3")
equation = sp.Eq(4 * x1 + 3 * x2 + 2 * x3, 1)
solution = sp.solve(equation, (x1, x2, x3))


if solution:
    sp.pprint("Solution:")
    sp.pprint(solution)
else:
    print("No solution found.")


Solution:
⎡⎛  3⋅x₂   x₃   1        ⎞⎤
⎢⎜- ──── - ── + ─, x₂, x₃⎟⎥
⎣⎝   4     2    4        ⎠⎦


In [3]:
# Assignment 2.C

import sympy as sp
x, y = sp.symbols('x y')
equation = sp.Eq(3*x - 6*y, 0)
solution = sp.solve(equation, (x, y))

print("Result: ")
print(solution)

Result: 
[(2*y, y)]


In [9]:
# Assignment 3.A
import numpy as np

def RowAdd(matrix, target_row, source_row, scalar):
    # Perform row addition operation
    matrix[target_row] += scalar * matrix[source_row]
    return matrix

def backward_substitution(matrix, b):
    # Perform backward substitution to solve the system of linear equations
    n = len(matrix)
    x = np.zeros(n)

    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(matrix[i, i + 1:], x[i + 1:])) / matrix[i, i]

    return x

A = np.array([[1, -1],
              [2, 1]])

b = np.array([0, 3])

A = RowAdd(A, 0, 1, -2)

solution = backward_substitution(A, b)
print("Solution vector x & y:")
print(solution)


Solution vector x & y:
[-3.  3.]


In [17]:
# Assignment 3.B
import numpy as np

def print_matrix(title, matrix):
    print(title)
    print(matrix, '\n')

def RowAdd(matrix, target_row, source_row, scalar):
    # Perform row addition operation
    matrix[target_row] += scalar * matrix[source_row]
    return matrix

def RowScale(matrix, target_row, scalar):
    # Perform row scaling operation
    matrix[target_row] *= scalar
    return matrix

def BackwardSubstitution(matrix, b):
    # Perform backward substitution to solve the system of linear equations
    n = len(matrix)
    x = np.zeros(n)

    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(matrix[i, i+1:], x[i+1:])) / matrix[i, i]

    return x

# Define the matrix A with dtype float64
A = np.array([[1, 5, -1],
              [-1, 1, -5],
              [2, 4, 4]], dtype=np.float64)

# Print the original matrix A
print_matrix("A (Original)", A)

# Create a copy of A for row operations
A_copy = A.copy()

# Perform row operations on the copy
A_copy = RowAdd(A_copy, 0, 1, 1)
print_matrix("A1", A_copy)

A_copy = RowAdd(A_copy, 0, 2, -2)
print_matrix("A2", A_copy)

A_copy = RowScale(A_copy, 1, 1/6)
print_matrix("A3", A_copy)

# Extract the last column of the modified matrix A to get the coefficient array for b
b = A_copy[:, -1]

# Note: Avoid further row operations since the matrix A has been modified, and additional operations may result in an inconsistent system.

# Perform backward substitution on the original matrix A
solution = BackwardSubstitution(A, b)

# Print the solution
print("Solution to vector x, y & z:")
print(solution)


A (Original)
[[ 1.  5. -1.]
 [-1.  1. -5.]
 [ 2.  4.  4.]] 

A1
[[ 0.  6. -6.]
 [-1.  1. -5.]
 [ 2.  4.  4.]] 

A2
[[ -4.  -2. -14.]
 [ -1.   1.  -5.]
 [  2.   4.   4.]] 

A3
[[ -4.          -2.         -14.        ]
 [ -0.16666667   0.16666667  -0.83333333]
 [  2.           4.           4.        ]] 

Solution to vector x, y & z:
[-33.83333333   4.16666667   1.        ]


In [21]:
# Assignment 3.C
import numpy as np

def print_matrix(title, matrix):
    print(title)
    print(matrix, '\n')

def RowAdd(matrix, target_row, source_row, scalar):
    # Perform row addition operation
    matrix[target_row] += scalar * matrix[source_row]
    return matrix

def RowScale(matrix, target_row, scalar):
    # Perform row scaling operation
    matrix[target_row] = matrix[target_row].astype(np.float64) * scalar
    return matrix

def BackwardSubstitution(matrix, b):
    # Perform backward substitution to solve the system of linear equations
    n = len(matrix)
    x = np.zeros(n)

    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(matrix[i, i + 1:], x[i + 1:])) / matrix[i, i]

    return x

# Define the matrix A with dtype float64
A = np.array([[2, 3, -1, -1],
              [1, 0, 1, 0],
              [-1, 2, -2, 0]], dtype=np.float64)

# Print the original matrix A
print_matrix("A (Original)", A)

# Perform row operations
A = RowScale(A, 0, 1/2)
print_matrix("A1", A)

A = RowAdd(A, 1, 0, -2)
print_matrix("A2", A)

A = RowAdd(A, 2, 0, 1)
print_matrix("A3", A)

A = RowScale(A, 1, -2/3)
print_matrix("A4", A)

A = RowAdd(A, 2, 1, -7/2)
print_matrix("A5", A)

# Correct the error in row operation
A = RowAdd(A, 2, 0, -3/2)
print_matrix("A6", A)

A = RowAdd(A, 2, 1, 1/2)
print_matrix("A7", A)

# Extract the last column of the modified matrix A to get the coefficient array for b
b = A[:, -1]

# Perform backward substitution to get the solution
solution = BackwardSubstitution(A[:, :-1], b)

# Print the solution
print("Solution to vector x_1, x_2 & x_3:")
print(solution)



A (Original)
[[ 2.  3. -1. -1.]
 [ 1.  0.  1.  0.]
 [-1.  2. -2.  0.]] 

A1
[[ 1.   1.5 -0.5 -0.5]
 [ 1.   0.   1.   0. ]
 [-1.   2.  -2.   0. ]] 

A2
[[ 1.   1.5 -0.5 -0.5]
 [-1.  -3.   2.   1. ]
 [-1.   2.  -2.   0. ]] 

A3
[[ 1.   1.5 -0.5 -0.5]
 [-1.  -3.   2.   1. ]
 [ 0.   3.5 -2.5 -0.5]] 

A4
[[ 1.          1.5        -0.5        -0.5       ]
 [ 0.66666667  2.         -1.33333333 -0.66666667]
 [ 0.          3.5        -2.5        -0.5       ]] 

A5
[[ 1.          1.5        -0.5        -0.5       ]
 [ 0.66666667  2.         -1.33333333 -0.66666667]
 [-2.33333333 -3.5         2.16666667  1.83333333]] 

A6
[[ 1.          1.5        -0.5        -0.5       ]
 [ 0.66666667  2.         -1.33333333 -0.66666667]
 [-3.83333333 -5.75        2.91666667  2.58333333]] 

A7
[[ 1.          1.5        -0.5        -0.5       ]
 [ 0.66666667  2.         -1.33333333 -0.66666667]
 [-3.5        -4.75        2.25        2.25      ]] 

Solution to vector x_1, x_2 & x_3:
[-0.5         0.33333333  1.   