**Name:** Eric Myles Panganiban<br>
**ID:** 21103306

In [9]:
# Pythonic Solutions
# the following functions are the steps involved in forward elimination
import numpy as np
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

# <font color = red> ASSIGNMENT 1</font>
- The above python functions are developed to automate forward elimination.
- To complete the process of determining the solution, create a function or steps of function that will automate backward substitution.

**Backward Substitution**

In [1]:
import numpy as np

def row_swap(A, k, l):
    
    B = np.copy(A).astype('float64')
    B[[k, l], :] = B[[l, k], :]
    return B

def row_scale(A, k, scale):
   
    B = np.copy(A).astype('float64')
    B[k, :] *= scale
    return B

def row_add(A, k, l, scale):
   
    B = np.copy(A).astype('float64')
    B[l, :] += B[k, :] * scale
    return B

def backward_substitution(A, b):
   
    n = A.shape[0]
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        sum_ax = np.dot(A[i, i+1:], x[i+1:])
        x[i] = (b[i] - sum_ax) / A[i, i]

    return x

A = np.array([[1, -1, 1, 3], [2, 1, 8, 18], [4, 2, -3, -2]])

# Add -2 times row 0 to row 1
A1 = row_add(A, 0, 1, -2)
print("A1")
print(A1, '\n')

# Add -4 times row 0 to row 2
A2 = row_add(A1, 0, 2, -4)
print("A2")
print(A2, '\n')

# Add -2 times row 1 to row 2
A3 = row_add(A2, 1, 2, -2)
print("A3")
print(A3, '\n')

# Multiply row 1 by 1/3
A4 = row_scale(A3, 1, 1.0/3)
print("A4")
print(A4, '\n')

# Multiply row 2 by 1/19
A5 = row_scale(A4, 2, 1.0/-19.)
print("A5")
print(A5, '\n')

# Use the backward substitution to find the solutions
solutions = backward_substitution(A5[:, :-1], A5[:, -1])
# Print the solutions
for i, sol in enumerate(solutions):
    print(f"x{i + 1} = {sol}")


A1
[[ 1. -1.  1.  3.]
 [ 0.  3.  6. 12.]
 [ 4.  2. -3. -2.]] 

A2
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   6.  -7. -14.]] 

A3
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   0. -19. -38.]] 

A4
[[  1.  -1.   1.   3.]
 [  0.   1.   2.   4.]
 [  0.   0. -19. -38.]] 

A5
[[ 1. -1.  1.  3.]
 [ 0.  1.  2.  4.]
 [-0. -0.  1.  2.]] 

x1 = 1.0
x2 = 0.0
x3 = 2.0


# <font color = red> Assignment 2 </font>
---
**INSTRUCTION**
- Use latex programming to show your manual solutions.
- If the problem involves determining the row echelon or reduced row echelon, show both the manual and the pythonic solutions.
- Solutions must be saved as a jupyter notebook.
- Push your solutions to your forked github repo.
- Note that there is some **possibility** that some ,or all, of your exam questions will be taken from these assignment.
- The technique here is to first solve manually before writing in Latex.
---

# **1. Provide reasons why each of the following equations is, or is not, a linear equation.**
- $\cos{\theta}x+4y+z = \sqrt{3}$ - **Not a linear equation** The linearity conditions are violated by both the cosine function and the term 4y.
- $cos{x}4y+z = \sqrt{3}$ - **Not a linear equation** The nonlinearity arises from the existence of the cosine function and the multiplication of y by 4.
- $x^{-1}+7y+z = \sin{(\frac{\pi}{2})}$ - **Not a linear equation** The presence of $x^{-1}$ and the sine function goes against the conditions of linearity.
- $x^1+y^1+z^1=0$ - **A linear equation** This equation is linear because the variables are raised to the first power, and the coefficients are all 1.

# **2. Find the solutions to the linear equations:**
- $2x_1+3x_2 =5$
    - $2_{x1} = 5 - 3_{x2}$
    - $x_1 = \frac{5 + 3_{x2}}{2}$
    - $3_{x2} = 5 - 2_{x1}$
    - $x_2 = \frac{5 - 2_{x1}}{3}$
- $4x_1+3x_2+2x_3=1$
    - $x_2 = s,x_3 = t$
    - $4_{x1} + 3s + 2t = 1$
    - $\begin{pmatrix}
      1 & 0 & 0 &\bigm| & \frac{1 - 3s - 2t}{4} \\
      0 & 1 & 0 &\bigm| & s \\
      0 & 0 & 1 &\bigm| & t \\
      \end{pmatrix}$
- $3x-6y=0$
    - $3x = 6y$
    - $x = \frac{6y}{3}$
    - $x = 2y$
    - $6y = 3x$
    - $y = \frac{3x}{6}$
    - $y = \frac{x}{2}$
    - $\begin{pmatrix}
      1 & 0 &\bigm| & 2s \\
      0 & 1 &\bigm| & s \\
      \end{pmatrix}$
      <br><br>

# **3. Solve the following systems of linear equations:**
- $L1: x - y = 0, \ L2: 2x + y = 3$

<br>

- $-2(x - y = 0)$
- $-2x + 2y = 0$

<br>

- $\frac{3y}{3} = \frac{3}{3}$
- $y = 1$

<br>

- $x - 1 = 0$
- $x = 1$

<br>

- $x = 1, \ y = 1$

In [3]:
import numpy as np

A, b = np.array([[1, -1], [2, 1]]), np.array([0, 3])
solution = np.linalg.solve(A, b)

print("Solution:\n", "x =", solution[0], "\n", "y =", solution[1])


Solution:
 x = 1.0 
 y = 1.0


- $L1: x + 5y = -1, \ L2: -x + y = -5, \ L3: 2x + 4y = 4$ <br><br>
 <br><br>
$
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    -1 & 1 &\bigm| & -5 \\
    2 & 4 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow[\text{R}_{3} - 2\text{R}_{1}]{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 6 &\bigm| & -6 \\
    0 & -6 &\bigm| & 6 \\
\end{pmatrix}
\xrightarrow[\text{R}_{3}(\frac{1}{6})]{\text{R}_{2}(\frac{1}{6})}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
    0 & -1 &\bigm| & 1 \\
\end{pmatrix}
\xrightarrow[\text{R}_{3} + \text{R}_{2}]{}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
    0 & 0 &\bigm| & 0 \\
\end{pmatrix}
% \xrightarrow[\text{R}_{1} - 5\text{R}_{2}]{}
% \begin{pmatrix}
%     1 & 0 &\bigm| & 4 \\
%     0 & 1 &\bigm| & -1 \\
%     0 & 0 &\bigm| & 0 \\
% \end{pmatrix}
$ 
<br><br> 
        - y = -1
<br>
<br>
        - x + 5(-1) = -1
        - x + -5 = -1
        - x = 5 + (-1)
        - x = 4
        - $x = 4, \ y = -1$

In [4]:
import numpy as np

coeff_matrix, constants = np.array([[1, 5], [-1, 1], [2, 4]]), np.array([-1, -5, 4])
solution = np.linalg.lstsq(coeff_matrix, constants, rcond=None)[0]

print("Solution:\n", "x =", solution[0], "\n", "y =", solution[1])


Solution:
 x = 4.000000000000001 
 y = -0.9999999999999998


- $L1: 2x_1 + 3x_2 - x_3 = -1, L2: x_1 + x_3 = 0, L3: -x_1 + 2x_2 - 2x_3  = 0$ <br><br>
<br><br>
$
\begin{pmatrix}
    2 & 3 & -1 &\bigm| & -1 \\
    1 & 0 & 1 &\bigm| & 0 \\
    -1 & 2 & -2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow[R_2 - R_1]{\frac{1}{2}R_1}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    0 & \frac{-3}{2} & \frac{3}{2} &\bigm| & \frac{1}{2}\\
    -1 & 2 & -2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow[\frac{-2}{3}R_2]{R_3 - \frac{7}{2}R_2}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    0 & 1 & -1 &\bigm| & \frac{-1}{3}\\
    0 & 0 & 1 &\bigm| & \frac{-5}{9} \\
\end{pmatrix}
\xrightarrow[R_1 - \frac{3}{2}R_2]{R_1 - \frac{1}{3}R_2}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & -1 &\bigm| & \frac{-1}{3}\\
    0 & 0 & 1 &\bigm| & \frac{-5}{9} \\
\end{pmatrix}
$
<br>
 <br>
        - x_1 = 0
        - $x_3 = -\frac{5}{9}$
        - $x_2 - x_3 = -\frac{1}{3}$ 
        - $x_2 - (-\frac{5}{9}) = -\frac{1}{3}$
        - $x_2 = -\frac{1}{3} - \frac{5}{9}$
        - $x_2 = -\frac{8}{9}$
        - $x_1 = 0, x_2 = -\frac{8}{9}, x_3 = -\frac{5}{9}$

**4. Provide reasons why the given matrices are either a row echelon, a reduced row echelon, or niether both.**<br>
---



a. <br>
\begin{pmatrix}
   1 & 0 & 1 \\
   0 & 0 & 3 \\
   0 & 1 & 0 \\
\end{pmatrix}<br><br>
b. <br>
\begin{pmatrix}
   7 & 0 & 1 & 0 \\
   0 & 1 & -1 & 4 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}<br><br>
c. <br>
\begin{pmatrix}
   0 & 1 & 3 & 0 \\
   0 & 0 & 0 & 1 \\
\end{pmatrix}<br><br>
d. <br>
\begin{pmatrix}
   0 & 0 & 0 \\
   0 & 0 & 0 \\
   0 & 0 & 0 \\
\end{pmatrix}<br><br>
e. <br>
\begin{pmatrix}
   1 & 0 & 3 & -4 & 0 \\
   0 & 0 & 0 & 0 & 0 \\
   0 & 1 & 5 & 0 & 1 \\
\end{pmatrix}<br><br>
f. <br>
\begin{pmatrix}
   0 & 0 & 1 \\
   0 & 1 & 0 \\
   1 & 0 & 0 \\
\end{pmatrix}<br><br>
g. <br>
\begin{pmatrix}
   1 & 2 & 3 \\
   1 & 0 & 0 \\
   0 & 1 & 1 \\
   0 & 0 & 1 \\
\end{pmatrix}<br><br>
h. <br>
\begin{pmatrix}
   2 & 1 & 3 & 5 \\
   0 & 0 & 1 & -1 \\
   0 & 0 & 0 & 3 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}
<br><br>


a. <br>
\begin{pmatrix}
   1 & 0 & 1 \\
   0 & 0 & 3 \\
   0 & 1 & 0 \\
\end{pmatrix}<br><br>

**Row Echelon Form**<br>
1.) There are no zero rows.<br>
2.) The leading entry of the second row (3) occurs to the right of the leading entry of the first row (1). Similarly, the leading entry of the third row (1) occurs to the right of the leading entry of the second row.<br>
3.) The leading entry in the first row is 1, the leading entry in the second row is 0 (which is allowed), and the leading entry in the third row is 1.

b. <br>
\begin{pmatrix}
   7 & 0 & 1 & 0 \\
   0 & 1 & -1 & 4 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}<br><br>

**Row Echelon Form**<br>
1.) All zero rows, if any, are at the bottom of the matrix.<br>
2.) The leading entry of each nonzero row occurs to the right of the leading entry of the previous row.<br>
3.) The leading entry in any nonzero row is 1.

c. <br>
\begin{pmatrix}
   0 & 1 & 3 & 0 \\
   0 & 0 & 0 & 1 \\
\end{pmatrix}<br><br>

**Not in Row Echelon Form and as well as Reduced Row Echelon Form**<br>
1.) The matrix fails the first condition because the leading entry in the second row (1) does not occur to the right of the leading entry in the first row (3).<br>
2.) The matrix fails the second condition because the leading entry in the second row (1) is not the only nonzero entry in its column.

d. <br>
\begin{pmatrix}
   0 & 0 & 0 \\
   0 & 0 & 0 \\
   0 & 0 & 0 \\
\end{pmatrix}<br><br>

**Reduced Row Echelon Form**<br>
1.) It is in row echelon form.<br>
2.) the leading entry in each nonzero is nonzero in its column

e. <br>
\begin{pmatrix}
   1 & 0 & 3 & -4 & 0 \\
   0 & 0 & 0 & 0 & 0 \\
   0 & 1 & 5 & 0 & 1 \\
\end{pmatrix}<br><br>

**Not in Row Echelon Form and as well as Reduced Row Echelon Form**<br>
1.) It does not satisfy the conditions 

f. <br>
\begin{pmatrix}
   0 & 0 & 1 \\
   0 & 1 & 0 \\
   1 & 0 & 0 \\
\end{pmatrix}<br><br>

**Reduced Row Echelon Form**<br>
1.) The first and second rows are non-zero<br>
2.) The leading entry of the second row (1) occurs to the right of the leading entry of the first row (1).<br>
3.) The leading entries in the first and second rows are the only nonzero entries in their respective columns.

g. <br>
\begin{pmatrix}
   1 & 2 & 3 \\
   1 & 0 & 0 \\
   0 & 1 & 1 \\
   0 & 0 & 1 \\
\end{pmatrix}<br><br>

**Not in Row Echelon Form and as well as Reduced Row Echelon Form**<br>
1.) It does not satisfy the conditions 

h. <br>
\begin{pmatrix}
   2 & 1 & 3 & 5 \\
   0 & 0 & 1 & -1 \\
   0 & 0 & 0 & 3 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}

**Not in Row Echelon Form and as well as Reduced Row Echelon Form**<br>
1.) It does not satisfy the conditions 

# **5. Solve the following systems of linear equations**

a.<br> 
<br>
$
 \begin{equation}
    \begin{bmatrix}
        1 & 2 & -3| 9\\
        2 & -1 & -1| 0\\
        4 & -1 & 1| 4\\
    \end{bmatrix}
    \xrightarrow[R_2 - 2R_1]{R_3 - 2R_2}
    \begin{bmatrix}
        1 & 2 & -3| 9\\
        0 & -5 & 5| 18\\
        0 & 1 & 3| 4\\
    \end{bmatrix}
    \xrightarrow[R_3 - R_2]{\frac{-1}{5}R_2}   
    \begin{bmatrix}
        1 & 2 & -3| 9\\
        0 & 1 & -1| \frac{18}{5}\\
        0 & 0 & 4| \frac{1}{4}R_3\\
    \end{bmatrix}
    \xrightarrow[R_1 - 2R_2]{R_2 + R_3}   
    \begin{bmatrix}
        1 & 0 & -3| \frac{8}{5}\\
        0 & 1 & 0| \frac{37}{10}\\
        0 & 0 & 1| \frac{1}{10}R_3\\
    \end{bmatrix}   
    \xrightarrow[]{R_1 + 3R_3} 
    \begin{bmatrix}
        1 & 0 & 0| \frac{19}{10}\\
        0 & 1 & 0| \frac{37}{10}\\
        0 & 0 & 1| \frac{1}{10}R_3\\
    \end{bmatrix}      
\end{equation}
$
<br>
- $x_1 = \frac{19}{10}$<br>
- $x_2 = \frac{37}{10}$<br>
- $x_3 = \frac{1}{10}$<br>
- $2x_1 - x_2 - x_3 = 0$<br>
- $\frac{19}{5} - \frac{37}{10} - \frac{1}{10} = 0$<br>

In [5]:
import numpy as np

A = np.array([[1, 2, -3],
              [2, -1, -1],
              [4, -1, 1]])

b = np.array([9, 0, 4])

solution = np.linalg.solve(A, b)

for i, x in enumerate(solution, start=1):
    print(f"x{i} = {x}")


x1 = 1.9
x2 = 3.6999999999999997
x3 = 0.10000000000000003


b. <br>
<br>
$
 \begin{equation}
    \begin{bmatrix}
        1 & 2 & 0| -1\\
        2 & 1 & 1| 1\\
        -1 & 1 & -1| -1\\
    \end{bmatrix}
    \xrightarrow[R_3 + R_2]{\frac{1}{2}R_2}
    \begin{bmatrix}
        1 & 2 & 0| -1\\
        0 & \frac{1}{2} & \frac{1}{2}| \frac{1}{2}\\
        0 & \frac{3}{2} & \frac{-1}{2}| \frac{-1}{2}\\
    \end{bmatrix}
    \xrightarrow[R_3 - R_2]{\frac{-1}{5}R_2}   
    \begin{bmatrix}
        1 & 2 & -3| 9\\
        0 & 1 & -1| \frac{18}{5}\\
        0 & 0 & 4| \frac{1}{4}R_3\\
    \end{bmatrix}
    \xrightarrow[R_3 + R_2]{R_2 - R_1}   
    \begin{bmatrix}
        1 & 0 & -3| \frac{8}{5}\\
        0 & 1 & 0| \frac{37}{10}\\
        0 & 0 & 1| \frac{1}{10}R_3\\
    \end{bmatrix}   
\end{equation}
$
- 0 + 0 + 0 cannot be equal to one

In [6]:
import numpy as np

M = np.array([[1, 2, 0],
              [2, 1, 1],
              [-1, 1, -1]])

if np.linalg.det(M) == 0:
    print("No solution")
else:
    print("Determinant of M:", np.linalg.det(M))


No solution


c. <br>
<br>
$
 \begin{equation}
    \begin{bmatrix}
        1 & -3 & 2| 0\\
        1 & 2 & 1| 0\\
        2 & 4 & 6| 0\\
    \end{bmatrix}
\end{equation}
$
- x_1 = 0, x_2 = 0, x_3 = 0
- x_1 - 3x_2 - 2x_3 = 0 
- 0 - 3(0) - 2(0) = 0
- 0
- x_1 + 2x_2 + x_3 = 0
- 0 + 2(0) + 0 = 0
- 0
- 2x_1 + 4x_2 + 6x_3 = 0
- 2(0) + 4(0) + 6(0) = 0
- 0

d. <br>
<br>
$
 \begin{equation}
    \begin{bmatrix}
        1 & 1 & 2 & 1| 1\\
        1 & -1 & -1 & 1| 0\\
        0 & 1 & 1 & 0| 1\\
        1 & 1 & 0 & 1| 2\\
    \end{bmatrix}
    \xrightarrow[R_4 - R_1]{R_2 - R_1}
    \begin{bmatrix}
        1 & 1 & 2 & 1| 1\\
        0 & -2 & -3 & 0| 1\\
        0 & 1 & 1 & 0| 1\\
        0 & 0 & -2 & 1| 1\\
    \end{bmatrix}
    \xrightarrow[R_3 + 2R_2]{R_2 <-> R_3}   
    \begin{bmatrix}
        1 & 1 & 2 & 1| 1\\
        0 & 1 & 1 & 0| 1\\
        0 & 0 & -1 & 0| 3\\
        0 & 0 & -2 & 1| 1\\
    \end{bmatrix}
\end{equation}
$
- y cannot be both 3 and $\frac{1}{-2}$, so there is no unique solution

In [7]:
import numpy as np

M = np.array([[1, 1, 2, 1],
              [1, -1, -1, 1],
              [0, 1, 1, 0],
              [1, 1, 0, 1]])

if np.linalg.det(M) == 0:
    print("Solution exists")
else:
    print("Determinant of M:", np.linalg.det(M))


Solution exists


# **6. Determine if the vectors are linear combinations**<br>

a. <br>
$
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} -1 \\ 3 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 2 \\ -6 \end{bmatrix}\\
\end{equation}
$
<br>
$
\begin{equation}
    \begin{bmatrix} 1 \\ 2 \end{bmatrix}x +
    \begin{bmatrix} -1 \\ 3 \end{bmatrix}y =
    \begin{bmatrix} 2 \\ -6 \end{bmatrix}
\end{equation}
$
<br>
<br>
$
\begin{equation}
    \begin{bmatrix}
        -1 & 2 & 1 \\
        3 & -6 & 2
    \end{bmatrix}
    \xrightarrow[]{\text{R}_{2} + 3\text{R}_{1}}
    \begin{bmatrix}
        -1 & 2 & 1 \\
        0 & 0 & 5
    \end{bmatrix}
\end{equation}
$
<br>
<br>- <font color=red>Not</font> a linear combination.<br>

In [8]:
import numpy as np

v = np.array([1, 2])
u2 = np.array([-1, 3])
u3 = np.array([2, -6])

coeff_matrix = np.vstack((u2, u3)).T
constants = v

if np.linalg.matrix_rank(coeff_matrix) == np.linalg.matrix_rank(np.column_stack((coeff_matrix, constants))):
    print("Vectors are Linearly Dependent!")
else:
    print("Vectors are Linearly Independent!")


Vectors are linearly independent.


b. <br>
$
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}
$
<br>
$
 \begin{equation}
    \begin{bmatrix}
        1 & 0 | 1\\
        1 & 1 | 2\\
        0 & 1 | 3\\
    \end{bmatrix}
    \xrightarrow[]{R_2 - x + 2_y = -12_x + y + z = 1 - x + y - z = -1}
    \begin{bmatrix}
        1 & 0 | 1\\
        1 & 1 | 1\\
        0 & 1 | 3\\
    \end{bmatrix}
    \xrightarrow[]{R_3 - R_2}   
    \begin{bmatrix}
        1 & 0 | 1\\
        0 & 1 | 1\\
        0 & 0 | 2\\
    \end{bmatrix}
\end{equation}
$
<br>- <font color=red>Not</font> a linear combination.<br>

In [9]:
import numpy as np

# Define the vectors
v = np.array([1, 2, 3])
u2 = np.array([1, 1, 0])
u3 = np.array([0, 1, 1])

# Create the coefficient matrix and the constant vector
coeff_matrix = np.vstack((u2, u3)).T
constants = v

# Check if there is a solution
if np.linalg.matrix_rank(coeff_matrix) == np.linalg.matrix_rank(np.column_stack((coeff_matrix, constants))):
    print("Vector is a Linear Combination!")
else:
    print("Vector isn't a Linear Combination!")

The vector is not a linear combination.


c. <br>
$
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 3 \\ 1 \\ -2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}
$
<br>
$
\begin{equation}
    \begin{bmatrix} 1 \\ 1 \\ 0\end{bmatrix}x +
    \begin{bmatrix} 0 \\ 1 \\ 1\end{bmatrix}y =
    \begin{bmatrix} 3 \\ 1 \\ -2\end{bmatrix}
\end{equation}
$
<br>
$
\begin{equation}
    \begin{bmatrix}
        1 & 0 & 3 \\
        1 & 1 & 1 \\
        0 & 1 & -2\\
    \end{bmatrix}
    x = 3,y = -2,x + y = 1x + y = 1 \xrightarrow[]{} 3 - 2 = 1
\end{equation}
$
<br>
$
\begin{equation}
    \begin{bmatrix} 3 \\ 3 \\ 0\end{bmatrix} +
    \begin{bmatrix} 0 \\ -2 \\ -2\end{bmatrix} =
    \begin{bmatrix} 3 \\ 1 \\ -2\end{bmatrix}
\end{equation}
$
<br>- <font color=green> A Linear Combination.</font><br>

In [23]:
import numpy as np

v = np.array([3, 1, -2])
u2 = np.array([0, -2, -2])
u3 = np.array([3, 1, -2])

coeff_matrix = np.vstack((u2, u3)).T
constants = v

if np.linalg.matrix_rank(coeff_matrix) == np.linalg.matrix_rank(np.column_stack((coeff_matrix, constants))):
    print("Vector is a Linear Combination!")
else:
    print("Vector isn't a Linear Combination!")

Vector is a Linear Combination!


# **7. Show that the following vectors are a span:** <br>

a.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 1 \\ \end{bmatrix}
\begin{bmatrix}1 \\ -1 \\ \end{bmatrix}
\end{pmatrix}
$
<br><br>
$
 \begin{equation}
    \begin{bmatrix}
        1 & 1 | x\\
        1 & -1 | y\\
    \end{bmatrix}
    \xrightarrow[]{}
    \begin{bmatrix}
        1 & 1 | x | R_1\\
        1 & -1 | y | R_2\\
    \end{bmatrix}
    \xrightarrow[R_2 - R_1]{\frac{1}{-2}R_2}
    \begin{bmatrix}
        1 & 1 | x | R_1\\
        0 & 1 | y | \frac{1}{-2}R_2\\
    \end{bmatrix}
\end{equation}
$
- <font color=green>Vectors are a span</font>
<br><br>

In [11]:
import numpy as np

v1 = np.array([1, 1])
v2 = np.array([1, -1])
arbitrary_vector = np.array([2, 3])

coeff_matrix = np.column_stack((v1, v2))
constants = arbitrary_vector

coefficients = np.linalg.solve(coeff_matrix, constants)

if np.allclose(coeff_matrix @ coefficients, constants):
    print("Vectors span the space.")
else:
    print("Vectors do not span the space.")


Vectors span the space.


b.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
<br><br>
$
 \begin{equation}
    \begin{bmatrix}
        1 & 1 & 0| x\\
        0 & 1 & 1| y\\
        1 & 0 & 1| z\\
    \end{bmatrix}
    \xrightarrow[]{R_3 - R_1}
    \begin{bmatrix}
        1 & 1 & 0| x\\
        0 & 1 & 1| y\\
        0 & -1 & 1| z - x\\
    \end{bmatrix}
    \xrightarrow[]{R_3 + R_2}   
    \begin{bmatrix}
        1 & 1 & 0| x\\
        0 & 1 & 1| y\\
        0 & 0 & 2| y - x + z\\
    \end{bmatrix}
\end{equation}
$
- <font color=green>Vectors are a span</font>
<br>

In [13]:
import numpy as np

v1, v2, v3 = np.array([1, 0, 1]), np.array([1, 1, 0]), np.array([0, 1, 1])
arbitrary_vector = np.array([2, 3, 4])

coeff_matrix = np.column_stack((v1, v2, v3))
constants = arbitrary_vector

coefficients = np.linalg.solve(coeff_matrix, constants)

if np.allclose(coeff_matrix @ coefficients, constants):
    print("Vectors span the space.")
else:
    print("Vectors do not span the space.")


Vectors span the space.


c.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
<br><br>
$
 \begin{equation}
    \begin{bmatrix}
        1 & 1 & 0| x\\
        0 & 1 & 1| y\\
        1 & 0 & 1| z\\
    \end{bmatrix}
    \xrightarrow[]{R_3 - R_1}
    \begin{bmatrix}
        1 & 1 & 0| x\\
        0 & 1 & 1| y\\
        0 & -1 & 1| z - x\\
    \end{bmatrix}
    \xrightarrow[]{R_3 + R_2}   
    \begin{bmatrix}
        1 & 1 & 0| x\\
        0 & 1 & 1| y\\
        0 & 0 & 2| y - x + z\\
    \end{bmatrix}
\end{equation}
$
- vectors are a span

In [14]:
import numpy as np

v1, v2, v3 = np.array([1, 0, 1]), np.array([1, 1, 0]), np.array([0, 1, 1])
arbitrary_vector = np.array([2, 3, 4])

coeff_matrix = np.column_stack((v1, v2, v3))
constants = arbitrary_vector

coefficients = np.linalg.solve(coeff_matrix, constants)

if np.allclose(coeff_matrix @ coefficients, constants):
    print("Vectors span the space.")
else:
    print("Vectors do not span the space.")


Vectors span the space.


# **8. Show that the following vectors are linearly independent:**<br><br>

a. <br>
$
\begin{equation}
\begin{bmatrix} 3 \\ -1 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} -1 \\ 2 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 1 \\ 1 \\ 3 \\ 1 \end{bmatrix}
\begin{bmatrix} -1 \\ -1 \\ 1 \\ 3 \end{bmatrix}
\end{equation}
$
- the following vectors are linearly independent. <br>

In [18]:
import numpy as np

def check_linear_independence(vectors):
    augmented_matrix = np.column_stack((vectors, np.zeros((len(vectors), 1))))
    return np.linalg.matrix_rank(vectors) == np.linalg.matrix_rank(augmented_matrix)

v1, v2, v3, v4 = np.array([0, 0, 0, 1]), np.array([0, 0, 2, 1]), np.array([0, 3, 2, 1]), np.array([4, 3, 2, 1])
vector_matrix = np.column_stack((v1, v2, v3, v4))

result = check_linear_independence(vector_matrix)

print("Vectors are" + (" " if result else " not ") + "Linearly Independent!")

Vectors are Linearly Independent!


b. <br>
$
\begin{equation}
\begin{bmatrix} 0 \\ 0 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 0 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 4 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\end{equation}
$
- L1: 4z = 0; z = 0
- L2: 3w + 3z; w = 0
- L3: 2y + 2w + 2z = 0; y = 0
- L4: x + 0 + 0 + 0 = 0; x = 0
- Therefore, the vectors are linearly independent by condition 1.

In [20]:
import numpy as np

def check_linear_independence(vectors):
    augmented_matrix = np.column_stack((vectors, np.zeros((len(vectors), 1))))
    return np.linalg.matrix_rank(vectors) == np.linalg.matrix_rank(augmented_matrix)

# Given vectors
v1, v2, v3, v4 = np.array([0, 0, 0, 4]), np.array([0, 0, 3, 3]), np.array([0, 2, 2, 2]), np.array([1, 1, 1, 1])
vector_matrix = np.column_stack((v1, v2, v3, v4))

result = check_linear_independence(vector_matrix)

print("Vectors are" + (" " if result else " not ") + "Linearly Independent!")


Vectors are Linearly Independent!


c. <br>
$
\begin{equation}
\begin{bmatrix} 1 \\ -1 \\ 1 \\ 0 \end{bmatrix}
\begin{bmatrix} -1 \\ 1 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 1 \\ 0 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 0 \\ 1 \\ -1 \\ 1 \end{bmatrix}
\end{equation}
$
- M = 4 & N = 4. are linearly independent by condidtion 4

In [21]:
import numpy as np

def check_linear_independence(vectors):
    augmented_matrix = np.column_stack((vectors, np.zeros((len(vectors), 1))))
    return np.linalg.matrix_rank(vectors) == np.linalg.matrix_rank(augmented_matrix)

# Given vectors
r1, r2, r3, r4 = np.array([1, -1, 1, 0]), np.array([-1, 1, 0, 1]), np.array([1, 0, 1, -1]), np.array([0, 1, -1, 1])
vector_matrix = np.column_stack((r1, r2, r3, r4))

# Check linear independence
result = check_linear_independence(vector_matrix)

print("Vectors are" + (" " if result else " not ") + "Linearly Independent!")


Vectors are Linearly Independent!
